[project]
name = "task-cli"
version = "1.0.0"
description = "Hello CLI"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
]

[project.scripts]
task-cli = "task_cli:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
